#!/usr/bin/env bash
#Updates the current state of the server
#Installs Nginx on the server
#restarts nginx

sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
